[project]
name = 'Traditional-Boat-Building-Knowledge'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.apprenticeship-tracking]
path = 'contracts/apprenticeship-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.builder-certification]
path = 'contracts/builder-certification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
